#development version of application
server:
  port: 8081

logging:
  level:
    org.springframework.web: debug

security:
  jwt:
    secret: ${JWT_SECRET:jhgfdcvbjmmnbvcxdfghjklkjhgfdiuytredsdfghkjhgfghkjhgfdsdfghjiop098765434567ujbvcxzcghjuiuytredcvgy7ujnhyt54edxde345tyuhbhu76j}
    issuer: ${JWT_ISSUER:substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:TRUE}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME-SITE:lax}